import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'appName': 'Fuel Cost Tracker',
      'mainScreenTitle': 'Fuel Cost Calculator',
      'historyScreenTitle': 'Trip History',
      'settingsScreenTitle': 'Settings',
      'mainTab': 'Home',
      'historyTab': 'History',
      'settingsTab': 'Settings',
      'distanceTraveled': 'Distance Traveled',
      'currentCost': 'Current Cost',
      'startTrip': 'Start Trip',
      'endTrip': 'End Trip',
      'kmUnit': 'km',
      'currencyUnit': 'SAR',
      'noTripsSaved': 'No saved trips yet.',
      'tripCostLabel': 'Cost',
      'tripDistanceLabel': 'Distance',
      'tripDurationLabel': 'Duration',
      'minuteUnit': 'min',
      'secondUnit': 'sec',
      'languageLabel': 'Language',
      'appearanceLabel': 'Appearance',
      'fuelSettingsLabel': 'Fuel Settings',
      'fuelPriceLabel': 'Fuel Price per Liter (SAR)',
      'carConsumptionSettingsLabel': 'Car Consumption Settings',
      'consumptionRateLabel': 'Consumption Rate',
      'kmPerLiter': 'km/L',
      'litersPer100Km': 'L/100km',
      'saveSettingsButton': 'Save Settings',
      'settingsSavedSuccess': 'Settings saved successfully',
      'consumptionPickerTitle': 'Select Consumption Rate',
      'doneButton': 'Done',
      'incomeLabel': 'Income',
      'netProfitLabel': 'Net Profit',
      'deleteConfirmationTitle': 'Confirm Deletion',
      'deleteConfirmationContent': 'Are you sure you want to delete this trip? This action cannot be undone.',
      'cancelButton': 'Cancel',
      'deleteButton': 'Delete',
      'tripDeletedSuccess': 'Trip deleted',
      'editTripIncomeTitle': 'Edit Trip Income',
      'saveChangesButton': 'Save Changes',
      'statsWeekly': 'Weekly',
      'statsMonthly': 'Monthly',
      'statsYearly': 'Yearly',
      'totalIncome': 'Total Income',
      'totalCost': 'Total Cost',
      'totalDistance': 'Total Distance',
      'totalNetProfit': 'Net Profit',
      'maintSettingsTitle': 'Periodic Maintenance Costs',
      'maintCostLabel': 'Maintenance Cost (SAR)',
      'maintIntervalLabel': 'Maintenance Interval (in km)',
      'totalTripCostLabel': 'Total Cost',
      'fuelLabel': 'Fuel',
      'maintLabel': 'Maint.',
      'enterTripIncomeTitle': 'Enter Trip Income',
      'skipButton': 'Skip',
      'saveButton': 'Save',
      'daySun': 'Sun', 'dayMon': 'Mon', 'dayTue': 'Tue', 'dayWed': 'Wed', 'dayThu': 'Thu', 'dayFri': 'Fri', 'daySat': 'Sat',
      'weekPrefix': 'W',
      'monthJan': 'Jan', 'monthFeb': 'Feb', 'monthMar': 'Mar', 'monthApr': 'Apr', 'monthMay': 'May', 'monthJun': 'Jun', 'monthJul': 'Jul', 'monthAug': 'Aug', 'monthSep': 'Sep', 'monthOct': 'Oct', 'monthNov': 'Nov', 'monthDec': 'Dec',
      'emptyHistoryTitle': 'No Trips Yet',
      'emptyHistorySubtitle': 'Start your first trip to see its record here!',
      'exportDataTitle': 'Export Data',
      'exportDataSubtitle': 'Save trip history as an Excel (CSV) file',
      'exportThisMonth': 'This Month',
      'exportLastMonth': 'Last Month',
      'exportThisYear': 'This Year',
      'exportAllTime': 'All Time',
      'exportButton': 'Export',
      'noDataToExport': 'No data to export for this period.',
      'exportShareText': 'Trips Report',
      'headerStartDate': 'Start Date',
      'headerStartTime': 'Start Time',
      'headerDuration': 'Duration (Minutes)',
      'headerDistance': 'Distance (km)',
      'headerIncome': 'Income (SAR)',
      'headerFuelCost': 'Fuel Cost (SAR)',
      'headerMaintCost': 'Maint. Cost (SAR)',
      'headerTotalCost': 'Total Cost (SAR)',
      'headerNetProfit': 'Net Profit (SAR)',
      'settingsCardGeneral': 'General',
      'settingsCardCalculation': 'Calculations & Vehicle',
      'settingsCardData': 'Data Management',
      'clearAllDataTitle': 'Clear All Data',
      'clearAllDataSubtitle': 'Permanently delete all saved trips',
      'clearDataConfirmationTitle': 'Confirm Deletion',
      'clearDataConfirmationContent': 'Are you sure? All trips and statistics will be permanently deleted and this action cannot be undone.',
      'dataClearedSuccess': 'All data cleared successfully',
      'dateToday': 'Today',
      'dateYesterday': 'Yesterday',
    },
    'ar': {
      'appName': 'حاسبة تكلفة الوقود',
      'mainScreenTitle': 'حاسبة تكلفة الوقود',
      'historyScreenTitle': 'سجل الرحلات',
      'settingsScreenTitle': 'الإعدادات',
      'mainTab': 'الرئيسية',
      'historyTab': 'السجل',
      'settingsTab': 'الإعدادات',
      'distanceTraveled': 'المسافة المقطوعة',
      'currentCost': 'التكلفة الحالية',
      'startTrip': 'بدء الرحلة',
      'endTrip': 'إنهاء الرحلة',
      'kmUnit': 'كم',
      'currencyUnit': 'ريال',
      'noTripsSaved': 'لا يوجد رحلات محفوظة بعد.',
      'tripCostLabel': 'التكلفة',
      'tripDistanceLabel': 'المسافة',
      'tripDurationLabel': 'المدة',
      'minuteUnit': 'دقيقة',
      'secondUnit': 'ثانية',
      'languageLabel': 'اللغة',
      'appearanceLabel': 'المظهر',
      'fuelSettingsLabel': 'إعدادات الوقود',
      'fuelPriceLabel': 'سعر لتر الوقود (بالريال)',
      'carConsumptionSettingsLabel': 'إعدادات صرفية السيارة',
      'consumptionRateLabel': 'معدل الصرفية',
      'kmPerLiter': 'كم / لتر',
      'litersPer100Km': 'لتر / 100 كم',
      'saveSettingsButton': 'حفظ الإعدادات',
      'settingsSavedSuccess': 'تم حفظ الإعدادات بنجاح',
      'consumptionPickerTitle': 'اختر معدل الصرفية',
      'doneButton': 'تم',
      'incomeLabel': 'الدخل',
      'netProfitLabel': 'صافي الربح',
      'deleteConfirmationTitle': 'تأكيد الحذف',
      'deleteConfirmationContent': 'هل أنت متأكد من رغبتك في حذف هذه الرحلة؟ لا يمكن التراجع عن هذا الإجراء.',
      'cancelButton': 'إلغاء',
      'deleteButton': 'حذف',
      'tripDeletedSuccess': 'تم حذف الرحلة',
      'editTripIncomeTitle': 'تعديل دخل الرحلة',
      'saveChangesButton': 'حفظ التعديل',
      'statsWeekly': 'أسبوعي',
      'statsMonthly': 'شهري',
      'statsYearly': 'سنوي',
      'totalIncome': 'إجمالي الدخل',
      'totalCost': 'إجمالي التكلفة',
      'totalDistance': 'إجمالي المسافة',
      'totalNetProfit': 'صافي الربح',
      'maintSettingsTitle': 'حساب تكاليف الصيانة الدورية',
      'maintCostLabel': 'تكلفة الصيانة (بالريال)',
      'maintIntervalLabel': 'فترة الصيانة (كل كم كيلومتر)',
      'totalTripCostLabel': 'التكلفة الإجمالية',
      'fuelLabel': 'وقود',
      'maintLabel': 'صيانة',
      'enterTripIncomeTitle': 'أدخل دخل الرحلة',
      'skipButton': 'تخطي',
      'saveButton': 'حفظ',
      'daySun': 'أحد', 'dayMon': 'اثنين', 'dayTue': 'ثلاثاء', 'dayWed': 'أربعاء', 'dayThu': 'خميس', 'dayFri': 'جمعة', 'daySat': 'سبت',
      'weekPrefix': 'أ',
      'monthJan': 'ينا', 'monthFeb': 'فبر', 'monthMar': 'مار', 'monthApr': 'ابر', 'monthMay': 'ماي', 'monthJun': 'يون', 'monthJul': 'يول', 'monthAug': 'اغس', 'monthSep': 'سبت', 'monthOct': 'اكت', 'monthNov': 'نوف', 'monthDec': 'ديس',
      'emptyHistoryTitle': 'لا يوجد رحلات بعد',
      'emptyHistorySubtitle': 'ابدأ رحلتك الأولى لترى سجلها هنا!',
      'exportDataTitle': 'تصدير البيانات',
      'exportDataSubtitle': 'حفظ سجل الرحلات كملف Excel (CSV)',
      'exportThisMonth': 'هذا الشهر',
      'exportLastMonth': 'الشهر الماضي',
      'exportThisYear': 'هذه السنة',
      'exportAllTime': 'كل الأوقات',
      'exportButton': 'تصدير',
      'noDataToExport': 'لا توجد بيانات للتصدير في هذه الفترة.',
      'exportShareText': 'تقرير الرحلات',
      'headerStartDate': 'تاريخ البدء',
      'headerStartTime': 'وقت البدء',
      'headerDuration': 'مدة الرحلة (دقائق)',
      'headerDistance': 'المسافة (كم)',
      'headerIncome': 'الدخل (ريال)',
      'headerFuelCost': 'تكلفة الوقود (ريال)',
      'headerMaintCost': 'تكلفة الصيانة (ريال)',
      'headerTotalCost': 'التكلفة الإجمالية (ريال)',
      'headerNetProfit': 'صافي الربح (ريال)',
      'settingsCardGeneral': 'عام',
      'settingsCardCalculation': 'الحسابات والمركبة',
      'settingsCardData': 'إدارة البيانات',
      'clearAllDataTitle': 'مسح كل البيانات',
      'clearAllDataSubtitle': 'حذف جميع الرحلات المحفوظة نهائياً',
      'clearDataConfirmationTitle': 'تأكيد المسح',
      'clearDataConfirmationContent': 'هل أنت متأكد؟ سيتم حذف جميع الرحلات والإحصائيات بشكل نهائي ولا يمكن التراجع عن هذا الإجراء.',
      'dataClearedSuccess': 'تم مسح جميع البيانات بنجاح',
      'dateToday': 'اليوم',
      'dateYesterday': 'الأمس',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant _AppLocalizationsDelegate old) => false;
}